server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimeZone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: hjklp123
  redis:
    host: localhost
    port: 6379
  mvc:
  view:
      suffix: ".html"
mybatis-plus:
  mapper-locations: mapper/*.xml
